### ISSUE TITLE
See roommate profiles

### ISSUE THREAD

**Issue by archang19** [cs130-w22/Group-B1#10]
## User Story
As a user, I want to conveniently see all the roommate profiles, so that I can see all the potential roommates that I could contact.

## Detailed Description
The user should also be able to perform a search using specific filters and criteria (first name, last name, email, area).

## Tasks
- [x] Create UI mockup for roommate search page #9
- [x] Set up Node #11
- [x] Backend REST API #22
- [x] Frontend for roommate search #25

## Acceptance Criteria
- [x] Given a user loads the roommate profile page and is logged in, the user should see all of the profiles 
- [x] Given a user searches based on first name, last name, area, or email, then the user should see the profiles that match the search filter
