### ISSUE TITLE
See recommended roommates

### ISSUE THREAD

**Issue by archang19** [cs130-w22/Group-B1#36]
## User Story
As a  user, I would look to see recommended roommates, so that I can save time.

## Detailed Description
The user should be able to see a list of ~10 recommended roommates. The list should be compiled based on some compatibility / similarity measure.

## Tasks
- [x] An endpoint must be created where given a username, a list of similar roommate profiles are returned #41 
- [x]  A frontend component must be created where a user can go to view similar profiles

## Acceptance Criteria
- [x] Given the user is logged in and on the roommate search page, the user should see a list of recommended roommates.
