### ISSUE TITLE
Creating user profile

### ISSUE THREAD

**Issue by archang19** [cs130-w22/Group-B1#5]
## User Story
As a user, I want to easily create my profile, so that other roommates can see my profile and reach out to me.

## Detailed Description
Provide additional details and context.

## Tasks
- [x] Create UI mockup for user profile page #6
- [x] Create UI mockup for user profile creation/editing page #7
- [x] Create UI mockup for user account creation / login page #8
- [x] Set up Node #11
- [x] Backend REST API #22
- [x] Frontend for signup/login #23
- [x] Frontend for updating existing profile #26

## Acceptance Criteria
- [x] Given a user enters a valid username, password, and necessary profile fields, the user can successfully create a roommate profile.
- [x] Given a user is logged in and has an existing profile, the user can update its profile.
