### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by IanConceicao** [cs130-w22/Group-B1#55]
## User Story
As a developer, I would like to view a page that contains documentation about important classes and functions so that I can understand the purpose of any key part of the project.

## Detailed Description
There should be a page that shows documentation for classes and functions. It should be easy to update as a developer and easy to read as a viewer. 

## Acceptance Criteria
- [x] Given a developer runs a specific command, then documentation should be automatically updated #54 
- [x] Given any important class or function on the **backend**, then the documentation should sufficiently explain the purpose of the class or function, and how to use it #56 
- [x] Given any important class or function on the **frontend**, then the documentation should sufficiently explain the purpose of the class or function #74
